name: Build + Unit Tests

on:
  push:
    branches: [chain4travel, dev]
  pull_request:
    tags-ignore: ["*"]
    branches: [chain4travel, dev]

jobs:
  run_build_unit_tests:
    name: build_unit_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19" # The Go version to download (if necessary) and use.
      - name: build_test
        shell: bash
        run: scripts/build_and_test.sh
      - name: fuzz_test
        shell: bash
        if: matrix.os == 'ubuntu-22.04' # Only run on Ubuntu 22.04
        run: | # Run each fuzz test 15 seconds
          cd ${{ github.workspace }}
          ./scripts/build_fuzz.sh 15
